spring.application.name=attendance

# Supabase PostgreSQL
spring.datasource.url=jdbc:postgresql://db.dknctpwehvdvtxkhyiuu.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}


Changes 1d0e418 ⟷ 6fd2f60 | 

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080